### ISSUE TITLE
Entity creation: when entity is not referenced by ID a misleading error message occurs

### ISSUE THREAD

**Issue by mariodavid** [Haulmont/jmix-rest#39]
When incorrectly referencing an entity not via ID, but rather another field the error message currently states this:

(lines[0].product.code is used instead of ID, which is wrong according to the current implementation) 

```
{
  "customer": {
    "id": "f88597ff-009d-1cf2-4a90-a4fb5b08d835"
  },
  "date": "2021-03-01",
  "amount": 130.08,
  "lines": [
    {
      "product": {
        "code": "outback_power_remote_power_system"
      },
      "quantity": 2
    }
  ]
}
```

results in the following error message:

```
HTTP 400

{
  "error": "Entity creation failed",
  "details": "Referenced entity for property 'customer' with id = 40c9a123-b182-0cbd-50bd-93b2002c284f is missing"
}
```

The error message states correctly that the customer reference is missing (which would be the nice shortcut feature), but furthermore, it shows an ID. This ID is actually the ID of the to-be-created Order instance. But the caller is not really aware of this ID whatsoever. Instead, it can be assumed that this is an ID of a customer that has been found or something.

So a better error message should be provided to not include the ID in case of entity creation.

**Comment by bulgakovea** [comment]
Removed entity ID from error message
