### ISSUE TITLE
Entity creation: not existing responseFetchPlan leads to HTTP 500 with no error for the client

### ISSUE THREAD

**Issue by mariodavid** [Haulmont/jmix-rest#41]
When a fetch plan is referenced as the response fetch plan, that is not existing in the application, the application returns HTTP 500. This is in particular problematic as it is not clear to the caller if the call succeeded or not. Without looking into the logs the conclusion might be: it has not been created as it threw HTTP 500.

```
POST http://localhost:8080/rest/entities/rstex11_Product?responseFetchPlan=notExistingFetchPlan

{
  "name": "Outback Power Remote Power System",
  "price": 99.95,
  "tags": [
    {
      "id": "333f3a20-c47b-4bc9-ba34-a72d2d815695"
    },
    {
      "id": "c4c028f0-fec1-7512-83cd-c17537d1f502"
    }
  ]
}
```

Actual behavior:

```
HTTP/1.1 500 

{
  "error": "Server error",
  "details": ""
}
```

Expected behavior:

Response Code is HTTP 201, as in fact the entity has been successfully created. The response body should contain the same content as if no responseFetchPlan has been added to the URL.

**Comment by alexbudarov** [comment]
IMHO in this case we should act fail-fast to early detect problems in frontend code.
- validate fetch plan name before executing entity operation
- return http 400 bad request with meaningful error message in json response
