### ISSUE TITLE
Bean Validation: @PastOrPresent error message misses invalidValue

### ISSUE THREAD

**Issue by mariodavid** [Haulmont/jmix-rest#43]
Given the following Bean validation:

```
@JmixEntity
@Table(name = "RSTEX11_ORDER")
@Entity(name = "rstex11_Order")
public class Order {

    @PastOrPresent
    @Column(name = "DATE_", nullable = false)
    @NotNull
    private LocalDate date;

   // ...
}
```

and the following request:
```

POST {{baseUrl}}
         /entities
         /rstex11_Order
Authorization: Bearer {{auth_token}}

{
  "date": "2022-01-01",
  "amount": 49.99
}
```
(the date is in the future `2022-01-01`)

Then the error message of the bean validation does not contain the `invalidValue`. Instead `null` is returned.
```
POST http://localhost:8080/rest/entities/rstex11_Order

HTTP/1.1 400 

[
  {
    "message": "javax.validation.constraints.PastOrPresent.message",
    "messageTemplate": "{javax.validation.constraints.PastOrPresent.message}",
    "path": "date",
    "invalidValue": null
  }
]
```

This is misleading as one might think that the server received `null` for the `date` attribute and therefore the validation kicked in (because null is neither past / present). But in fact, the server received the correct value but just did not return the received value.

**Comment by bulgakovea** [comment]
Can't reproduce

**Comment by owlet1997** [comment]
Enviroment:
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2798-211
IntelliJ version: IntelliJ IDEA 2021.1 (Community Edition)

Issue was reproduced:

TC:
1. Open attached project -> run app
2. Open postman -> send POST request to http://localhost:8080/oauth/token?grant_type=password&username=admin&password=admin
3. Send POST request to http://localhost:8080/rest/entities/r_NewEntity with JSON body:
```
{
  "date": "2022-01-01",
  "name": "first"
}
```

AR:
![image](https://user-images.githubusercontent.com/45730069/116043614-f3b9d900-a680-11eb-90e9-25be23e4f203.png)

Test project: [restexc.zip](https://github.com/Haulmont/jmix-rest/files/6374979/restexc.zip)
