### ISSUE TITLE
Bulk Create / Update Entities: Multiple Bean Validation violations are only shown for one of the entities

### ISSUE THREAD

**Issue by mariodavid** [Haulmont/jmix-rest#47]
GIven the following request:

```
POST {{baseUrl}}
         /entities
         /rstex11_Customer
Authorization: Bearer {{auth_token}}

[
  {
    "name": null
  },
  {
    "name": null
  }
]
```

Note: The name is a required field for the Customer entity.

The following response is created:

```
HTTP/1.1 400 

[
  {
    "message": "may not be null",
    "messageTemplate": "{javax.validation.constraints.NotNull.message}",
    "path": "name",
    "invalidValue": null
  }
]
```

Expected behavior:

* a list of all violations of all entities that have been part of the request
* the path should indicate somehow about which list item this problem belongs to (similar to how it is described here: https://github.com/Haulmont/jmix-rest/issues/45)

Example:

```
HTTP/1.1 400 

[
  {
    "message": "may not be null",
    "messageTemplate": "{javax.validation.constraints.NotNull.message}",
    "path": ".[0].name",
    "invalidValue": null
  },
  {
    "message": "may not be null",
    "messageTemplate": "{javax.validation.constraints.NotNull.message}",
    "path": ".[1].name",
    "invalidValue": null
  }
]
```

NOTE: I have only tested it for creating entities, but I strongly assume that the endpoint behalves similar in the bulk update case, as the behavior seems to be related to the bean validation.

**Comment by Desire456** [comment]
After https://github.com/Haulmont/jmix-rest/issues/78 resolved need to reuse the validation fragment for a bulk update too
