### ISSUE TITLE
 Batch entities commit should save all entities in a single transaction

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-rest#49]
Right now each of the passed entities is saved in a separate transaction. That may cause problems if one of save operation fails - it will be unclear which entities have been saved and which haven't.

CUBA issue: https://github.com/cuba-platform/restapi/issues/124

**Comment by andreysubbotin** [comment]
For QA: check only saving multiple entities in one request. Separately saving in one transaction does not need to be checked.
