### ISSUE TITLE
Download Files with access_token as URL parameter can lead to HTTP 401

### ISSUE THREAD

**Issue by mariodavid** [Haulmont/jmix-rest#51]
Sometimes the obtainted access token contains characters that lead to problems when using the token as part of the URL

Example:

Given the following access token: `yoLzD/W9Jlq7+0/UAdkK7IMJjVA=`

When performing the request do download a file with the access token in the URL (as described here: https://files.cuba-platform.com/swagger/7.1/#!/Files/post_files) with an URL encoded access token parameter:

```
GET http://localhost:8080/rest/files?fileRef=fs%3A%2F%2F2021%2F03%2F11%2F2791bd27-b821-f103-4572-da4530041509.jpg%3Fname%3Dcat.jpg&access_token=yoLzD%2FW9Jlq7+0%2FUAdkK7IMJjVA%3D

HTTP/1.1 401 
Cache-Control: no-store
Pragma: no-cache
WWW-Authenticate: Bearer realm="oauth2-resource", error="invalid_token", error_description="Invalid access token: yoLzD/W9Jlq7 0/UAdkK7IMJjVA="
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: DENY
Content-Type: application/json
Transfer-Encoding: chunked
Date: Thu, 11 Mar 2021 10:13:24 GMT
Keep-Alive: timeout=60
Connection: keep-alive
{
  "error": "invalid_token",
  "error_description": "Invalid access token: yoLzD/W9Jlq7 0/UAdkK7IMJjVA="
}
Response code: 401; Time: 185ms; Content length: 98 bytes
```

Authentication failed. In the error message, it shows the interpreted access token: `yoLzD/W9Jlq7 0/UAdkK7IMJjVA=`

They are the same, but just the `+` sign is not correctly transferred.

Depending on which access token is generated, it sometimes works and sometimes not. So it is also pointing to the fact that it is dependent on which characters the token contains.

**Comment by bulgakovea** [comment]
When using this method, the access token must be encoded into _UTF-8_ before insert into URL.

Example:

Given the following access token:  `yoLzD/W9Jlq7+0/UAdkK7IMJjVA=`

After encoding, the token will look like this: `yoLzD%2FW9Jlq7%2B0%2FUAdkK7IMJjVA%3D`
