### ISSUE TITLE
FileRef: both spaces and + signs in file name are encoded as +

### ISSUE THREAD

**Issue by cuba-frontend** [Haulmont/jmix-rest#61]
### Steps to Reproduce

Upload a file with name `+ + +.txt`

### AR

FileRef is:

```
fs://2021/03/26/c2ed2af7-7b71-60f5-b6df-351d3d15fd1a.txt?name=+++++.txt
```

When an entity with a file attribute is loaded (e.g. using `GET /entities/<entityName>/<id>`) only the above `fileRef` string is returned, which makes it impossible to construct the correct file name at frontend.

### ER

Spaces are replaced with `%20` and `+` with `%2B`, i.e. `+ + +` becomes `%2B%20%2B%20%2B`, which can be safely decoded at frontend.

**Comment by glebshalyganov** [comment]
File name containing spaces or reserved characters should be URL-encoded when passing as a query param.
