### ISSUE TITLE
Change "Internal Server Error" to "Access Denied" in case user doesn't have permissions to login via rest

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-rest#67]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2775-211
IntelliJ version: IntelliJ IDEA 2021.1 (Community Edition)

TC:
run app> create a new user with  minimal role
via postman send `http://localhost:8080/oauth/token?grant_type=password&username=new&password=1`
ER: "Access Denied"
AR: 
```
{
    "error": "server_error",
    "error_description": "Internal Server Error"
}
```

**Comment by knstvk** [comment]
If the user has no `rest.enabled` specific permission, HTTP 403 Forbidden is returned. Tested on latest 1.2.0-SNAPSHOT.
