### ISSUE TITLE
rest/messages/entities does not respect Accept-Language header

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-rest#69]
**To reproduce:**

Send a GET request to `rest/messages/entities` with `Accept-Language` header equal to `ru`.

**ER:**

Messages are in Russian.

**AR:**

Messages are in English:

**Comment by artemglinov** [comment]
@vyacheslav-pushkin  Can you specify the behaviour you expect? I created a custom entity and response localization works as it should in a brand new app. System entities obviously shouldn't be localized (and they are included in a response). Did you mean that entities of the System Level must be excluded when processing the request?

**Comment by vyacheslav-pushkin** [comment]
@artemglinov I'll see if I can reproduce the problem again and let you know.

**Comment by vyacheslav-pushkin** [comment]
@artemglinov It can be reproduced on [scr-jmix](https://github.com/jmix-projects/scr-jmix). 

Sending

```
curl -X 'GET' 'http://localhost:8080/rest/messages/entities' -H 'accept: application/json' -H 'authorization: Bearer RX91lJqmLK0u_HzfL8-1O-MT70o' -H 'Accept-Language: ru'
```

results in:

```
"scr$Car":"Car",
   "scr$Car.carType":"Type",
   "scr$Car.createdBy":"Created by",
   "scr$Car.createdDate":"Created date",
   "scr$Car.ecoRank":"Eco Rank",
   "scr$Car.garage":"Garage",
```

whereas an expectation is to have [Russian names](https://github.com/jmix-projects/scr-jmix/blob/master/src/main/resources/com/company/scr/messages_ru.properties) for entities and attributes.

**Comment by artemglinov** [comment]
@vyacheslav-pushkin Here, the problem is connected with an absent localization property: see [https://docs.jmix.io/jmix/0.x/localization/message-bundles.html](https://docs.jmix.io/jmix/0.x/localization/message-bundles.html). It is enough to add `jmix.core.availableLocales = en,ru` in application.properties (as in the docs). Then, the bug disappears.
